Iter5
kosalnik/metrics pull request #5
Opened 2024-03-03 11:44 UTC by kosalnik

2024-03-04 11:23 UTC, rktkov requested changes

2024-03-04 11:23 UTC, rktkov commented on internal/storage/memstorage.go
> +func (m *MemStorage) GetGauge(name string) float64 {
Я бы использовал нотацию похожую на получение значения по ключу из мапы. Это позволит убрать лишние методы из интерфейса. Сделать методы Get, чтобы они возвращали либо значение, либо  булевый флаг, который бы указывал на наличие элемента.

2024-03-04 11:23 UTC, rktkov commented on internal/server/server.go
> +	"github.com/go-chi/chi/v5"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-03-04 11:23 UTC, rktkov commented on internal/metricprovider/collector.go
> +func GetMetrics() map[string]float64 {
Я бы пакет переименовал в просто  metric

2024-03-04 11:23 UTC, rktkov commented on internal/client/client.go
> +		log.Printf("fail push. %s", err.Error())
тут надо бы выйти из метода.
а закрытие потока с телом ответа вызвать с помощью оператора defer

2024-03-04 11:23 UTC, rktkov commented on internal/client/client.go
> +	if err != nil {
см. комментарий выше.

2024-03-04 11:23 UTC, rktkov commented on internal/config/config.go
> +type AgentConfig struct {
Из названия можно убрать слово Config, указатель уже есть в имени пакета.

2024-03-05 11:24 UTC, kosalnik commented on internal/storage/memstorage.go
> +func (m *MemStorage) GetGauge(name string) float64 {
fixed

2024-03-05 11:24 UTC, kosalnik commented on internal/server/server.go
> +	"github.com/go-chi/chi/v5"
fixed

2024-03-05 11:24 UTC, kosalnik commented on internal/metricprovider/collector.go
> +func GetMetrics() map[string]float64 {
fixed

2024-03-05 11:24 UTC, kosalnik commented on internal/client/client.go
> +	if err != nil {
fixed

2024-03-05 11:25 UTC, kosalnik commented on internal/config/config.go
> +type AgentConfig struct {
fixed

2024-03-06 23:08 UTC, rktkov approved these changes

2024-03-07 05:48 UTC, merged